language: groovy
sudo: false
jdk:
- oraclejdk7
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx1024m -Xms256m -XX:MaxPermSize=372m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
install: /bin/true
script:
- ./travis-build.sh
cache:
  directories:
  - $HOME/.gradle
